<NotepadPlus>
    <Session activeView="1">
        <mainView activeIndex="5">
            <File firstVisibleLine="40" xOffset="0" scrollWidth="352331" startPos="221" endPos="222" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\start.php" backupFilePath="" originalFileLastModifTimestamp="1543200040" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="16777217" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="12" xOffset="0" scrollWidth="352331" startPos="4835" endPos="4846" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\lib\x\config.php" backupFilePath="" originalFileLastModifTimestamp="1543898014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="19" scrollWidth="917" startPos="1058" endPos="1058" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\lib\php\autoloader.php" backupFilePath="" originalFileLastModifTimestamp="1543964500" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="16777217" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="63" xOffset="0" scrollWidth="595" startPos="1778" endPos="1778" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\lib\php\SessionFunctions.php" backupFilePath="" originalFileLastModifTimestamp="1543384631" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="2" xOffset="0" scrollWidth="1071" startPos="7496" endPos="7496" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\lib\php\CheckLogin.php" backupFilePath="" originalFileLastModifTimestamp="1543963855" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1139900416" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1064" startPos="237" endPos="281" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\lib\php\CheckLogout.php" backupFilePath="" originalFileLastModifTimestamp="1543963897" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="847" startPos="984" endPos="984" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\signup.php" backupFilePath="" originalFileLastModifTimestamp="1543899642" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="16777217" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="847" startPos="726" endPos="747" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\login.php" backupFilePath="" originalFileLastModifTimestamp="1543963935" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="352331" startPos="125" endPos="125" selMode="0" lang="Normal Text" encoding="-1" filename="C:\wamp64\www\Skeleton\dev\TODO.txt" backupFilePath="" originalFileLastModifTimestamp="1543979441" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="72" xOffset="0" scrollWidth="933" startPos="2799" endPos="2799" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\lib\php\db.php" backupFilePath="" originalFileLastModifTimestamp="1542947715" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1137836032" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1659" startPos="904" endPos="904" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\lib\html\Frame.php" backupFilePath="" originalFileLastModifTimestamp="1543901501" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="819" startPos="246" endPos="246" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\main.php" backupFilePath="" originalFileLastModifTimestamp="1543514222" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="16777217" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1071" startPos="196" endPos="205" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\lib\php\Session.php" backupFilePath="" originalFileLastModifTimestamp="1543513903" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="3014698" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="136" xOffset="0" scrollWidth="1071" startPos="2982" endPos="2982" selMode="0" lang="PHP" encoding="-1" filename="C:\wamp64\www\Skeleton\lib\php\CheckSignup.php" backupFilePath="" originalFileLastModifTimestamp="1543979209" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="16777217" mapWrapIndentMode="-1" mapIsWrap="no">
                <Mark line="8" />
            </File>
        </subView>
    </Session>
</NotepadPlus>
